# Generated by Django 6.0.1 on 2026-01-20 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_dish_options_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='dish_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Фото блюда'),
        ),
    ]
