# Generated by Django 6.0.1 on 2026-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше значение, тем выше позиция на странице', verbose_name='Место на странице'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше значение, тем выше позиция на странице', verbose_name='Место на странице'),
        ),
    ]
